"""Set usage_count to NOT NULL in Category model

Revision ID: 516912622298
Revises: d7c2382300d4
Create Date: 2024-08-12 13:41:46.848178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516912622298'
down_revision = 'd7c2382300d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('usage_count',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('usage_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
