"""Add skill_levels, is_active and is_finalized fields to GameSession model

Revision ID: 8cd77b8e8520
Revises: 516912622298
Create Date: 2024-08-13 09:25:12.819942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd77b8e8520'
down_revision = '516912622298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_finalized', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('skill_levels', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.drop_column('skill_levels')
        batch_op.drop_column('is_finalized')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
