"""Add response_times field to GameSession model for tracking question response times

Revision ID: bb3ee2a8f3fc
Revises: 8cd77b8e8520
Create Date: 2024-08-14 10:54:11.705006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb3ee2a8f3fc'
down_revision = '8cd77b8e8520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_times', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.drop_column('response_times')

    # ### end Alembic commands ###
